### ISSUE TITLE
Having issue with public accessor in other package

### ISSUE THREAD

**Issue by francishero** [SumeetMoray/Nearby-Shops-Shop-Owner-Android-app#1]
![35177eb62a9064e3bf9fc6dc86b4108](https://user-images.githubusercontent.com/16598693/60365431-45f52900-9a1b-11e9-8eda-350c4672b583.png)
I tried to run the project its failing with that error in the screenshot, what could be wrong? thanks

**Comment by SumeetMoray** [comment]
thank you ... i have fixed it ... you can checkout the updated code !
